version: "3.7"

services:

  database:
    image: mongo
    networks:
      - database
    volumes:
      - $PWD/data:/data/db


  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - database
    ports: 
      - "8585"
    environment:
      SERVICE_NAME: webserver
      ADDRESS: $ADDRESS
      MONGO_DSN: $MONGO_DSN
      API_SERVER_ADDRESS: $API_SERVER_ADDRESS
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
    depends_on:
      - database


networks:
  envoymesh: {}
  database: {}

